name: final_project
dependencies:
  - python>=3.10
  - pip
  - pip:
      - pandas
      - numpy
      - keras
      - kaggle
      - matplotlib
      - scikit-learn
      - sklearn
      - tensorflow
      - scipy
      - altair
      - streamlit
#    - -r requirements.txt