name: final_project
dependencies:
  - pip
  - pandas
  - numpy
  - keras
  - kaggle
  - matplotlib
  - scikit-learn
  - tensorflow
  - scipy
  - altair
  - streamlit
#  - pip:
#    - -r requirements.txt